=== ecaterina99/Java/MarshallingAndUnmarshallingTest/src/main/xsd/country.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="country" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="country">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="capital" type="xs:string" />
                <xs:element name="description" type="xs:string" />
                <xs:element name="population" type="xs:string"/>
                <xs:element  ref="ruler" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="countryCode" type="stringMaxSize2"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="stringMaxSize2">
        <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="ruler">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ruler_name" type="xs:string"/>
                <xs:element name="date_of_birth" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ecaterina99/Java/MarshallingAndUnmarshallingTest/country.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="src/main/xsd/country.xsd">
    <country countryCode="sr">
        <name>Serbia</name>
        <capital>Belgrade</capital>
        <description>Serbia is.....</description>
        <population>1238457</population>
        <ruler>
            <ruler_name>Dan T</ruler_name>
            <date_of_birth>1954-07-17+11:44</date_of_birth>
        </ruler>
    </country>
    <country countryCode="fr">
        <name>France</name>
        <capital>Paris</capital>
        <description>France is.....</description>
        <population>5838457</population>
        <ruler>
            <ruler_name>Iron G</ruler_name>
            <date_of_birth>1978-07-17+11:44</date_of_birth>
        </ruler>
    </country>
</root>
